### ISSUE TITLE
Add the comments

### ISSUE THREAD

**Issue by alphabin** [ChuckBerryOnTop/BerriesAndCream#23]
We need to comment our code guys @jeffreylee87  @asilva21 @dkubiak1 , also we need to delete the uncommented code

**Comment by alphabin** [comment]
im working on this !

**Comment by jeffreylee87** [comment]
added some notes, if you guys want to add more please do, but that's all i could find as of now.

**Comment by asilva21** [comment]
comments added and we are current.
